__version__ = "0.2.1b1"

from .pattern_search import run_pattern_search
from .parser_registry import (
    get_parse_files,
    list_parsers,
    parse_files,
    parse_files_quiet,
)
from .mensural_backend import parse_files_mensural
from .verovio_backend import parse_files_verovio
from .verovio_render import (
    get_toolkit as vrv_get_toolkit,
    vrv_set_options,
    vrv_guess_input_from,
    vrv_load_data,
    vrv_load_from_file,
    vrv_load_from_url,
    vrv_convert_to_mei,
    vrv_render_page,
    vrv_render_all_pages,
    vrv_display_svg,
    vrv_quiet,
    vrv_find_elements_at_time,
    vrv_timemap,
    vrv_get_mei,
    vrv_set_mei,
    vrv_mask_mei_to_ids,
    vrv_render_selection_excerpt,
    vrv_render_symbolic_selection,
    vrv_insert_annot,
    vrv_has_mei_export,
    vrv_set_additional_css,
    vrv_highlight_ids,
    vrv_crop_svg_to_ids,
    vrv_crop_svgs_to_ids,
    vrv_debug_info,
    vrv_inject_highlight_css,
    vrv_insert_annot_plist,
    vrv_insert_annots_by_tstamps,
    vrv_process_annotations,
    vrv_namespaces,
)
from .overlay import (
    select_metric_df,
    kernel_from_variants,
    compute_top_matches_df,
    build_match_records,
    build_overlay_source,
    overlay_top_matches_on_piano_roll,
)
from .analysis_utils import (
    parse_pitch_name,
    name_to_midi,
    midi_to_name,
    build_pitch_counts,
    sort_pitch_counts,
    plot_pitch_distribution,
    display_pitch_distribution,
    build_pc_counts_from_names,
    build_pitch_class_distributions,
    display_pitch_class_distributions,
    build_duration_counts,
    plot_duration_distribution,
    display_duration_distribution,
    display_filtered_piano_roll,
    extract_selected_xml_ids,
    check_monophonic_input,
    melodic_interval_distribution,
    display_melodic_interval_distribution,
    build_onset_position_counts,
    display_onset_position_histogram,
)
from .timeline_backend import (
    TimelineParseResult,
    humdrum_rap_to_timeline,
    parse_rap_humdrum_file,
    parse_rap_humdrum_source,
    parse_files_timeline,
    build_timeline_duration_counts,
    build_timeline_onset_position_counts,
    add_timeline_rhythm_analysis,
    timeline_to_mei,
    save_timeline_mei,
    load_timeline_mei_with_verovio,
    find_duplicate_mei_xml_ids,
)
from .parser_utils import (
    expand_file_sources,
    format_parsed_summary,
    print_parsed_summary,
)
from .conversion import (
    DownloadOptions,
    MidiImportOptions,
    convert_sources,
    print_conversion_summary,
    set_validation_stage,
)
from .midi_timing import MidiTimingResult, read_midi_timing
from .facsimile_viewer import (
    FacsimileViewerCache,
    FacsimileUnavailableError,
    InteractiveFacsimileViewer,
    build_facsimile_viewer,
    build_verovio_options,
    find_camat_root,
    launch_interactive_facsimile_viewer,
    read_facsimile_model,
    render_verovio_pages,
    resolve_mei_source,
)
from .check_mei_consistency import Finding, MeiChecker, check_mei_files
from .convert_harm_startid_to_tstamp import (
    ConversionResult as HarmConversionResult,
    HarmConversion,
    convert_file as convert_harm_startid_to_tstamp,
    normalize_figured_bass_accidentals,
)
from .link_pb_to_surface import (
    PbSurfaceResult,
    PbSurfaceRow,
    link_file as link_pb_to_surface,
)
from .mei_consistency_workflow import (
    MEI_CMN_51_SCHEMA,
    VEROVIO_REPORT_COLUMNS,
    CleanupResult,
    SchemaValidationResult,
    VerovioLogResult,
    apply_safe_cleanup,
    load_report,
    normalize_single_layer_number_copies,
    report_summary,
    resolve_mei_inputs,
    run_checker,
    run_relaxng_validation,
    run_verovio_warning_check,
    source_snippet,
)
from .facsimile_downloader import download_images as download_facsimile_images
from .integrate_measure_annotations import (
    get_body_measures,
    get_measure_alignment_report,
    integrate_annotation_file,
    parse_mei,
    validate_measure_alignment,
)
from .page_filter import (
    filter_mei_files,
    page_in_ranges,
    page_number_for_path,
    parse_page_ranges,
)
from .upload_and_integrate_measure_annotations import (
    DETECTOR_URL,
    SkipFile as MeasureDetectionSkip,
    build_annotation_tree,
    process_mei_file as detect_and_integrate_mei,
)
from .validate_iiif_vs_local import (
    IIIF_IMAGE_URL_TEMPLATE,
    find_image_for_stem,
    parse_graphic_from_output_mei,
    read_image_size,
    sha256_bytes,
    sha256_file,
)
from .mensural_utils import (
    DEFAULT_MENSURAL_DURATION_MAP,
    inject_default_meter_signature_in_mei_text,
    inject_default_meter_signature_in_mei_file,
    normalize_mensural_durations_in_mei_text,
    normalize_mensural_durations_in_mei_file,
    normalize_mensural_mei_for_partitura_text,
    normalize_mensural_mei_for_partitura_file,
)

__all__ = [
    '__version__',
    'run_pattern_search',
    'get_parse_files',
    'list_parsers',
    'parse_files',
    'parse_files_quiet',
    'parse_files_mensural',
    'parse_files_verovio',
    'vrv_get_toolkit',
    'vrv_set_options',
    'vrv_guess_input_from',
    'vrv_load_data',
    'vrv_load_from_file',
    'vrv_load_from_url',
    'vrv_convert_to_mei',
    'vrv_render_page',
    'vrv_render_all_pages',
    'vrv_display_svg',
    'vrv_quiet',
    'vrv_find_elements_at_time',
    'vrv_timemap',
    'vrv_get_mei',
    'vrv_set_mei',
    'vrv_mask_mei_to_ids',
    'vrv_render_selection_excerpt',
    'vrv_render_symbolic_selection',
    'vrv_insert_annot',
    'vrv_has_mei_export',
    'vrv_set_additional_css',
    'vrv_highlight_ids',
    'vrv_crop_svg_to_ids',
    'vrv_crop_svgs_to_ids',
    'vrv_debug_info',
    'vrv_inject_highlight_css',
    'vrv_insert_annot_plist',
    'vrv_insert_annots_by_tstamps',
    'vrv_process_annotations',
    'vrv_namespaces',
    'select_metric_df',
    'kernel_from_variants',
    'compute_top_matches_df',
    'build_match_records',
    'build_overlay_source',
    'overlay_top_matches_on_piano_roll',
    'parse_pitch_name',
    'name_to_midi',
    'midi_to_name',
    'build_pitch_counts',
    'sort_pitch_counts',
    'plot_pitch_distribution',
    'display_pitch_distribution',
    'build_pc_counts_from_names',
    'build_pitch_class_distributions',
    'display_pitch_class_distributions',
    'build_duration_counts',
    'plot_duration_distribution',
    'display_duration_distribution',
    'display_filtered_piano_roll',
    'extract_selected_xml_ids',
    'check_monophonic_input',
    'melodic_interval_distribution',
    'display_melodic_interval_distribution',
    'build_onset_position_counts',
    'display_onset_position_histogram',
    'TimelineParseResult',
    'humdrum_rap_to_timeline',
    'parse_rap_humdrum_file',
    'parse_rap_humdrum_source',
    'parse_files_timeline',
    'build_timeline_duration_counts',
    'build_timeline_onset_position_counts',
    'add_timeline_rhythm_analysis',
    'timeline_to_mei',
    'save_timeline_mei',
    'load_timeline_mei_with_verovio',
    'find_duplicate_mei_xml_ids',
    'expand_file_sources',
    'format_parsed_summary',
    'print_parsed_summary',
    'DownloadOptions',
    'MidiImportOptions',
    'convert_sources',
    'print_conversion_summary',
    'set_validation_stage',
    'MidiTimingResult',
    'read_midi_timing',
    'FacsimileViewerCache',
    'FacsimileUnavailableError',
    'InteractiveFacsimileViewer',
    'build_facsimile_viewer',
    'build_verovio_options',
    'find_camat_root',
    'launch_interactive_facsimile_viewer',
    'read_facsimile_model',
    'render_verovio_pages',
    'resolve_mei_source',
    'Finding',
    'MeiChecker',
    'check_mei_files',
    'HarmConversion',
    'HarmConversionResult',
    'convert_harm_startid_to_tstamp',
    'normalize_figured_bass_accidentals',
    'PbSurfaceResult',
    'PbSurfaceRow',
    'link_pb_to_surface',
    'MEI_CMN_51_SCHEMA',
    'VEROVIO_REPORT_COLUMNS',
    'CleanupResult',
    'SchemaValidationResult',
    'VerovioLogResult',
    'apply_safe_cleanup',
    'load_report',
    'normalize_single_layer_number_copies',
    'report_summary',
    'resolve_mei_inputs',
    'run_checker',
    'run_relaxng_validation',
    'run_verovio_warning_check',
    'source_snippet',
    'download_facsimile_images',
    'get_body_measures',
    'get_measure_alignment_report',
    'integrate_annotation_file',
    'parse_mei',
    'validate_measure_alignment',
    'filter_mei_files',
    'page_in_ranges',
    'page_number_for_path',
    'parse_page_ranges',
    'DETECTOR_URL',
    'MeasureDetectionSkip',
    'build_annotation_tree',
    'detect_and_integrate_mei',
    'IIIF_IMAGE_URL_TEMPLATE',
    'find_image_for_stem',
    'parse_graphic_from_output_mei',
    'read_image_size',
    'sha256_bytes',
    'sha256_file',
    'DEFAULT_MENSURAL_DURATION_MAP',
    'inject_default_meter_signature_in_mei_text',
    'inject_default_meter_signature_in_mei_file',
    'normalize_mensural_durations_in_mei_text',
    'normalize_mensural_durations_in_mei_file',
    'normalize_mensural_mei_for_partitura_text',
    'normalize_mensural_mei_for_partitura_file',
]
